severity:
  - HIGH
  - CRITICAL

exit-code: 1
ignore-unfixed: true

skip-dirs:
  - node_modules
  - .git
  - .omc

scanners:
  - vuln
  - secret
  - misconfig

db:
  skip-update: false
  download-java-db: false
